FACTOR_NAMES = [
    "topic_snack",           # [0]
    "topic_time",            # [1]
    "topic_place",           # [2]
    "topic_person",          # [3]
    "topic_evidence",        # [4]
    "topic_alibi",           # [5]
    "action_ask",            # [6]
    "action_suspect",        # [7]
    "action_observe",        # [8]
    "emotion_nervous",       # [9]
    "emotion_honest",        # [10]
    "emotion_deflect",       # [11]
    "personality_open",      # [12]
    "personality_impulsive", # [13]
    "reserved_1",            # [14]
    "reserved_2",            # [15]
]
